### ISSUE TITLE
How much memory needed for training?

### ISSUE THREAD

**Issue by hwd8868** [yukitsuji/3D_CNN_tensorflow#1]
I used tensorflow-CPU for training dataset with 48G memory. But I get memory fault after training for several hours :
terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc

**Comment by yukitsuji** [comment]
I train by GPU with 6G memory.
what is your batchsize for training?

**Comment by hwd8868** [comment]
Batch size is 5, the default value. 
Now I decrease batch size to 2, also get the same error.
I didn't modify your code,  just run it first.

**Comment by hwd8868** [comment]
Batch size is 5, the default value.
Now I decrease batch size to 2, also get the same error.
I  just run it first, didn't modify your code,

**Comment by yukitsuji** [comment]
I don't know how to resolve this issue.
Please refer other pages about this.

And probably this could help you.
https://github.com/tensorflow/tensorflow/issues/9487

**Comment by hwd8868** [comment]
Ok, thank you. I just found 48G memory was fully used.

**Comment by hwd8868** [comment]
Ok, thank you. I just found 48G memory was fully used.
