### ISSUE TITLE
Why do we invert the matrices in the proj_to_velo function in input_velodyne.py

### ISSUE THREAD

**Issue by MeghaMaheshwari** [yukitsuji/3D_CNN_tensorflow#10]

**Comment by ansabsheikh9** [comment]
Hi, In kitti raw dataset we have labels in left camera frame. so we need a transformation from camera frame to velodyne frame.

**Comment by MeghaMaheshwari** [comment]
Thanks. Could you also clarify, which angle from the bin file are you trying to take in the function 
def filter_camera_angle(places):
    """Filter camera angles for KiTTI Datasets"""
    bool_in = np.logical_and((places[:, 1] < places[:, 0] - 0.27), (-places[:, 1] < places[:, 0] - 0.27))
    # bool_in = np.logical_and((places[:, 1] < places[:, 0]), (-places[:, 1] < places[:, 0]))
    return places[bool_in]
and why are you restricting to this field. Is it because you want to align it to the left  camera angle?

**Comment by ansabsheikh9** [comment]
yes it is filtering out the points which are outside the camera view angle
