### ISSUE TITLE
bird-view projection

### ISSUE THREAD

**Issue by toby147642** [yukitsuji/3D_CNN_tensorflow#15]
I have confirmed code again and again, and couldn't find the projection of object. But there are images which project the object to the bird view.
May I ask how to write the bird-view projection's code?
Thanks a lot!

**Comment by yukitsuji** [comment]
There is no image in this project.
Visualization in this project used RViz and ROS.

If you want to write bird-view projection's code,
1. only remove z axis information (Bird view need not to use height information)
2. Save as image using opencv

**Comment by toby147642** [comment]
Thank you for your answer.
But I still cannot figure out how to use ROS to complete the visualization.
Is the visualization code in input_velodyne.py and use the function publish_pc2?
The visualization code is also supposed to be written by myself, is that right?
Your answer may help me a lot, thx!

**Comment by toby147642** [comment]
Okay, I will try it.
