### ISSUE TITLE
Visualize during test time

### ISSUE THREAD

**Issue by pfrcks** [yukitsuji/3D_CNN_tensorflow#16]
Hi,

I was wondering if you could tell about how to visualize the result during test time. I know how to use ROS to visualize LIDAR data, but during test when the data starts being outputted to ROS, I am unable to see it in RViz.

**Comment by ansabsheikh9** [comment]
I think you can try to set reference frame

**Comment by ansabsheikh9** [comment]
rosrun tf static_transform_publisher 0 0 0 0 0 0 1 map velodyne 10

**Comment by pfrcks** [comment]
hey @ansabsheikh9 thank you for replying. so based on your suggestion here is what i did.
used 

        pcd_path = "../data/testing/velodyne/002397.bin"                                                                                                                                           
        calib_path = "../calib/testing/calib/002397.txt"                                                                                                                                           
        test(1, pcd_path, label_path=None, resolution=0.1, calib_path=calib_path, dataformat="bin", is_velo_cam=True, \                                                                            
            scale=8, voxel_shape=(800, 800, 40), x=(0, 80), y=(-40, 40), z=(-2.5, 1.5))       

to test the model.

started `roscore` , followed by `python model_01_deconv.py` followed by `rosrun tf static_transform_publisher 0 0 0 0 0 0 1 map velodyne 10` followd by `rviz`

I then added a pointcloud to rviz and selected `velodyne` as fixed frame and `/points_raw` as topic in the pointckoud.

I am able to see a static pointcloud formation which changes if i change topic to `/points_raw1`

Am i doing something wrong? Also how do I add the identified cars to the visualization(through bounded boxes)     

![screenshot from 2018-04-24 13-04-43](https://user-images.githubusercontent.com/10297394/39202607-64ae1aae-47c0-11e8-8067-03211fbc17c0.png)
![screenshot from 2018-04-24 13-06-52](https://user-images.githubusercontent.com/10297394/39202609-67889e5c-47c0-11e8-9ad3-7c2c0d01d6ae.png)

**Comment by pfrcks** [comment]
hi @ansabsheikh9 thank you so much. it really cleared my doubts. :)

I have just one other query. There is no function definition for the the function `filter_car_data`, due to which I am unable to use `train_test()`. Any idea about this?

**Comment by ansabsheikh9** [comment]
#4 here you can have a look at the solution mentioned by @yukitsuji

**Comment by pfrcks** [comment]
@ansabsheikh9 thank you so much for your replies. They have been very helpful to me.

I wanted to evaluate the model after training but I do not think that there is any code present in this repo which gives the accuracy of the model. 
Do you have an idea as to how I could get the accuracy of the model?

**Comment by ansabsheikh9** [comment]
I think you have to write the code for this, you can use KITTI evaluation code, provided in dev kit aswell. If you find anything please update me aswell.
