### ISSUE TITLE
ImportError: No module named std_msgs.msg

### ISSUE THREAD

**Issue by ljd16** [yukitsuji/3D_CNN_tensorflow#3]
There is a error as the title shows when I run
`python model_01_deconv.py`

output
```
3D_CNN_tensorflow/input_velodyne.py", line 10, in <module>
    import std_msgs.msg
ImportError: No module named std_msgs.msg
```
so, where is the std_msgs?

**Comment by yukitsuji** [comment]
Please install ROS in your environment.
Google it.

**Comment by ljd16** [comment]
Thank you!
The problem has been solved.
