### ISSUE TITLE
Which dataset should I use?

### ISSUE THREAD

**Issue by adioshun** [yukitsuji/3D_CNN_tensorflow#5]
hi. 

the download link in the README.md is a image detection datasets. 
- http://www.cvlibs.net/datasets/kitti/eval_object.php

There are 3D and bird-eye view datasets. which one should I use?

One more, in the each datasets pages, there are also multiple files. Do I need all files? 

Could you tell me the  specific files name or link? 

Thanks

**Comment by yukitsuji** [comment]
Please download 3d detection dataset. 
(http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d)

In this project, left images, lidar data, calibration files and training labels are required.

**Comment by adioshun** [comment]
Thanks a lot :)

**Comment by yukitsuji** [comment]
@ansabsheikh9 
sorry, this project don't use image dataset.
