### ISSUE TITLE
support rotate angle detect and classify

### ISSUE THREAD

**Issue by githubuse** [yukitsuji/3D_CNN_tensorflow#6]
hi, from the detect result , it looks like not support detect vehicle with rotate angle, and also didn't support classify, right ?  I see other object types(like pedestrian) were filtered except vehicle.
Thanks

**Comment by yukitsuji** [comment]
>  it looks like not support detect vehicle with rotate angle, and also didn't support classify, right ? 
Yes. Instead of predicting angle, this model predict 8 Vertices(24 element: xyz).

And this project predict vehicle places only, so don't classify other classes.
