### ISSUE TITLE
about the environment of the computer

### ISSUE THREAD

**Issue by shouwangzhuang** [yukitsuji/3D_CNN_tensorflow#8]
hello, excuse me !
I am a newer of the python,  when  i run the programs , it always have some errors, maybe i have a wrong with my computer running environment,Could you tell me the operating system and the version of python and tensorflow? I want to learn it ,thank you very much!

**Comment by yukitsuji** [comment]
sorry, I forget the version of tensorflow.

Ubuntu 14.04
Python2
tensorflow ????

**Comment by yukitsuji** [comment]
@shouwangzhuang Could you share the error messages?

**Comment by shouwangzhuang** [comment]
Thank you for your reply，let me try it again ，i will share the error if it does not work.
