### ISSUE TITLE
hi, can you tell me how to do the evaluation with 8 pose points?

### ISSUE THREAD

**Issue by ywangeq** [yukitsuji/3D_CNN_tensorflow#9]
I use the kitti datasets to train, and can not do its evaluation code by 8 points. So can you tell me how do you do the evaluation?

**Comment by yukitsuji** [comment]
In this repository, I don't provide any evaluation code. So you should write by yourself.

**Comment by ansabsheikh9** [comment]
Hi @yukitsuji, How can we implement NMS? is there any method which works on oriented bounding boxes?
Thanks

**Comment by yukitsuji** [comment]
I think it is difficult to implement nms for oriented bounding boxes.
Shapely is the library for computational geometry and includes iou calculation for rotated rectangles.
https://toblerity.org/shapely/manual.html
